### ISSUE TITLE
Double encoding setting was removed in last commit

### ISSUE THREAD

**Issue by flo-mic** [coreruleset/auto-decoding-plugin#4]
I just noticed that the double encoding setting in rule "9501010" was removed during the last plugin update. The file with this configuration was removed and the new config file for the plugin disabling was added. But the existing configuration settings are not moved to the new file. The following configuration was removed: https://github.com/coreruleset/auto-decoding-plugin/blob/d1c202270b6f993e5729230407030021feade430/plugins/generic-transformations-config-before.conf#L25

**Comment by dune73** [comment]
Thank you for reporting.

I've created https://github.com/coreruleset/auto-decoding-plugin/pull/6 to address this.

Would you mind checking if it works for you. 

Also: Please notice that the variable has been renamed.
